on: 
  schedule:
    - cron: "0 * * * *"


permissions:
  id-token: write
  contents: read

name: "El Vocero Scraper"

jobs:
  scraper:
    name: Scrape "El Vocero"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOWNLOAD_PAT }}

    - name: Download "El Vocero" container
      id: download-elvocero-container
      run: |
        docker pull ${{ secrets.ELVOCERO_IMAGE }}
    
    - name: Run "El Vocero" container
      id: run-elvocero-container
      run: |
        docker run ${{ secrets.ELVOCERO_IMAGE }}
      


