on: 
  schedule:
    - cron: "0 * * * *"


permissions:
  id-token: write
  contents: read

name: "ENDI Scraper"

jobs:
  scraper:
    name: Scrape "ENDI"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOWNLOAD_PAT }}

    - name: Download "ENDI" container
      id: download-endi-container
      run: |
        docker pull ${{ secrets.ENDI_CONTAINER_IMAGE }}
    
    - name: Run "ENDI" container
      id: run-endi-container
      run: |
        docker run ${{ secrets.ENDI_CONTAINER_IMAGE }}
      


