on: 
  schedule:
    - cron: "0 * * * *"


permissions:
  id-token: write
  contents: read

name: "ENDI Scraper"

jobs:
  scraper:
    name: Scrape "ENDI"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install AWS CLI
      id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2     
        verbose: false 

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Authenticate with ECR
      id: auth-ecr
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }}| \
        docker login --username AWS --password-stdin ${{ secrets.ACCOUNT_ID}}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Download "ENDI" container
      id: download-endi-container
      run: |
        docker pull ${{ secrets.ENDI_CONTAINER_IMAGE }}
    
    - name: Run "ENDI" container
      id: run-endi-container
      run: |
        docker run ${{ secrets.ENDI_CONTAINER_IMAGE }}
      


